---
name: Scrape Falcosecurity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - run: go run . -p falcosecurity
      - uses: EndBug/add-and-commit@v9
        with:
          message: update falcosecurity .csv metrics
          default_author: github_actions