---
name: Scrape Falcosecurity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - run: go run . -p falcosecurity
      - uses: peter-evans/create-pull-request@v5-rc
        with:
          signoff: true
          branch: update/falcosecurity
          base: main
          title: 'update(kernels): update falcosecurity .csv metrics'
          body: 'This PR updates the metrics in .csv for falcosecurity packages'
          commit-message: 'update(kernels): update falcosecurity .csv metrics'
          token: ${{ secrets.GITHUB_TOKEN }}
